version: "3"
services:
  homeassistant-qq:
    build: .
    container_name: homeassistant-qq
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "8080:8080"
    volumes:
      - ./.env.local:/app/.env:ro
      - ./data/napcat/videos:/data/napcat/videos
    hostname: homeassistant-qq
    networks:
      - homeassistant-qq-network
    depends_on:
      - napcat

  napcat:
    image: mlikiowa/napcat-docker:latest
    container_name: napcat
    restart: unless-stopped
    ports:
      - "3001:3001"
      - "6099:6099"
    volumes:
      - ./data/napcat/data:/app/.config/QQ/NapCat/data
      - ./data/napcat/config:/app/napcat/config
      - ./data/cache:/cache
      - ./data/napcat/videos:/data/napcat/videos
    mac_address: "02:42:ac:14:00:02"
    hostname: napcat
    networks:
      - homeassistant-qq-network

networks:
  homeassistant-qq-network:
    driver: bridge
